server:
  port: 1111
  
  
  servlet:
    context-path: /config
  
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/krishnareddy390/microservice
          username: krishna.reddy390@gmail.com
          password: Krishna9030@
          
